### ISSUE TITLE
passwords error

### ISSUE THREAD

**Issue by gitusertf** [Bre77/badrcm#6]
I'm getting the following errors after adding servers (screencap to follow):

[HTTP 404] https://127.0.0.1:8089/servicesNS/sa-tfuiuc/badrcm/storage/passwords/sh-i-0bd683db03aa0a862.dev-whatever.splunkcloud.com %3Asa-tfuiuc%3A?output_mode=json&count=1
![Snag_c37395](https://github.com/Bre77/badrcm/assets/86369190/f06eda60-895a-4cbe-b1ed-c71e93e8339d)

**Comment by gitusertf** [comment]
And I tried deleting the configured remote server, it would not let me.  I also removed the entire badrcm app and reinstalled but the servers reappeared!  Is information being stored in the KV store somewhere and needs to be cleared out?

**Comment by gitusertf** [comment]
Nevermind, got it working.

**Comment by gitusertf** [comment]
Nevermind, got it working.

**Comment by Bre77** [comment]
I think you had a space in the servers hostname. Glad you got it working.
